server:
  port : ${PORT:8080}

spring:
  main:
    banner-mode: off
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${USER_DB:admin}
    password: ${DB_PASSWORD:123}
    url: jdbc:postgresql://${DB_HOSTNAME:localhost}:5432/rinha
    hikari:
      maximum-pool-size: ${DB_INITIAL_POOL_SIZE:100}
      minimum-idle: {DB_INITIAL_POOL_SIZE:10}
      idle-timeout: 30000
      connection-timeout: 20000
  jpa:
    defer-datasource-initialization: true
    generate-ddl: true
    hibernate.ddl-auto: update
    properties:
      jakarta.persistence.query.timeout: 10000
    show-sql: false

logging:
  level:
    root: ${LOG_LEVEL:INFO}